language: node_js
node_js:
- 8.9.0
branches:
  only:
  - master
install:
- yarn install
before_script:
- yarn global add gulp
script:
- gulp test
notifications:
  slack:
    secure: sEPigkYODYIMz6vNGfvm6BhdCrLLEtcv9SNbsClxV0GaI5qvkEwdNR4qzaq0uJV0ofVyxts84vv1GVaDlT6xYnrZBi7Gu10IehXW08IaIGWTnfNzlbHEaHt5gOUUTG9B1MNtwWulSKA2Zuf52k2XikpI+LOvcy8qir7hemnR1pp/8aPvvllIz5qU41R10bbQJzl+fHmcrI5OD2jR9+0eZ8OPICfrf7u/rPb2zsfQmmYULkaCPF5W3MxgHVlyuyqRTULqMivmt5CgyVALkOEXnCo2mo02ID4Z38y1QBCKQzox0Lq2on66e89ZinIr+NkcI8Qs64EXW90xF5WD8ISndsPwKjk5RCaolaE2oAOOwnmWO7IbHKHFGkLNcoJ6RE9fK8kVjlvWqnzz0hkOQjnI3KeCiYQxjK9ldgHBGWXhCwMoNisTUdAp+vU/8W8nXKU5tZ+a3HsyCClLApZtrvoIK7R9z2Vvzca5RyqvLHxK8rDKI+5egKpaKFnubuVoNnsrS79yfRsCBvWYuott0DV8QArQ82ykqq20XJjZFstEzaY5il/hA5rxZtWqvK9ZO1X94kcGRT2nWdbeEniSIcrmu2hqluE10qPNJx8dTm0Rbo2NnESgcczJATZ/IE4aDJY1fFJFnzvywjMzjIZaCQdJDFMScaK9MU9X2auH3LxU7eQ=
deploy:
  skip_cleanup: true
  provider: npm
  email: devadmin@goverb.com
  api_key:
    secure: KV2R2aUyCY+Ul25ET5ZHnKBJwuOulh6CJSz960x31EZZQkC4DyyTsF0PqrqH8TGds/KrevdxOpTf/R0c4fbcn+S3oP9TMsT243a+T0YHX55yzNuvMcFgbJzz4c8iCIXvD1DoHKWfxn9TIBZPYDyMhjitLP4qyUs9k/WnjWX3NJFz4hlw5X27jByOxyxeStrMo2dG/beXsgH5ss95u3MUPjQSEU4zM11r3ZA3SeWojEstPN12ynOD/IqRdp56B0FSNpEAxM6eRgJVonkwT8zt2FMVmpryJjJi+XvMnW0lHPEFjI9CCVlwIkruD68XJ+v5+QF+8VvYU8UKB6Ib6VY6wuxqhbQVHk6tJ8txv48EDnzKTbzBu7yv5lP/ngEAAMLC/u32T6+vr/gYXRR/nhXAZMV8Zfd8fADiyAUHliFvbqC+z1qtEM1+wTdIZL4DosWAy4E4JwlnGltBS2z4ILJGPOiPNlgK8pFG8ArRH1fctBqxLugWe/d+0PGWFaS1uUxf6WO0BL1On5nq/EjqKguyLcF4dTnyyS0cS6EhSUJX0g3zKczxKjU0bqjdETgES3XxUo1/Pusr7kgc82JSEGKzzlDV1//y1nOFwpoS+Y0OlKWlG02aRyopFiOHPRvbMV/5VkfinvbI5LpYpvqp5kZ45WZMFp04QAW8VxmvY12hz0A=
  on:
    tags: true
    repo: goVerb/docker-deployer
