language: node_js
node_js:
- 8.9.0
branches:
  only:
  - master
install:
- yarn install
before_script:
- yarn global add gulp
script:
- gulp test
- gulp npmrc
after_success:
- npm publish
notifications:
  slack:
    secure: sEPigkYODYIMz6vNGfvm6BhdCrLLEtcv9SNbsClxV0GaI5qvkEwdNR4qzaq0uJV0ofVyxts84vv1GVaDlT6xYnrZBi7Gu10IehXW08IaIGWTnfNzlbHEaHt5gOUUTG9B1MNtwWulSKA2Zuf52k2XikpI+LOvcy8qir7hemnR1pp/8aPvvllIz5qU41R10bbQJzl+fHmcrI5OD2jR9+0eZ8OPICfrf7u/rPb2zsfQmmYULkaCPF5W3MxgHVlyuyqRTULqMivmt5CgyVALkOEXnCo2mo02ID4Z38y1QBCKQzox0Lq2on66e89ZinIr+NkcI8Qs64EXW90xF5WD8ISndsPwKjk5RCaolaE2oAOOwnmWO7IbHKHFGkLNcoJ6RE9fK8kVjlvWqnzz0hkOQjnI3KeCiYQxjK9ldgHBGWXhCwMoNisTUdAp+vU/8W8nXKU5tZ+a3HsyCClLApZtrvoIK7R9z2Vvzca5RyqvLHxK8rDKI+5egKpaKFnubuVoNnsrS79yfRsCBvWYuott0DV8QArQ82ykqq20XJjZFstEzaY5il/hA5rxZtWqvK9ZO1X94kcGRT2nWdbeEniSIcrmu2hqluE10qPNJx8dTm0Rbo2NnESgcczJATZ/IE4aDJY1fFJFnzvywjMzjIZaCQdJDFMScaK9MU9X2auH3LxU7eQ=
env:
  global:
    secure: CcmF5lzt6Gv25rOac9OGdvzzw3VNcCqT5Ab4loHZpmc+JlK060fr7cyvmAx3wKdm8nTysMXLeHQZf+gqR7f5dSuCJfA34KUWUdf0+diAoLcuZOrlDzOU2Xwtd1NzHQilPiXmCSmLJEltquEpJBn1qBkMoIxrX/hYZi6IjCSA0ZjGpZP79wkK3S0nW2/WyKTI/DxPkVLE7HfA2SEnjXnH1uunQyd1NOSj3ng5R4dEta1K7yrEeHnZ1FkRMFHccMteqFEGpQDuT/eT/iXUAH5t2MbIjs6U02JxUjxqgE4SpvUdoLyD72MYmx73jNLl+sa2yKtAx3OTlLakKcQtLEYpG9P6o/RBG0QHCu+bLV2gLcb2pmipeQgsSW2Q2yShQl8MS/Hf7R3fp0+IyuIa4TuZoBi0cmndURc5b8XQtzbBepdxPH6nw/ZLNJxZgXPfdwPAMKiVIzEnf4V/MtLP9jGtSB5iih0tP8CJQHd2mc7CR6mB7CSYbWGKW238l/g0FDPof8BCKpqWqRe1KclyfOluwH+86NdkE1L6r7rlTLSLA/1Ib1cMgK7UySsRCEWlDaw0PiSFCGYUehUCzQ1vgJuinrvq0VJ5s9fjZhynQoAcj3Pk/ENtZPQAq8+lPkWZFJnfsN2QSDtaIf8DCgykjFoTUZKmYGysBlrSlBMY9AMmAJs=
