language: node_js
node_js:
- 8.9.0
branches:
  only:
  - master
install:
- yarn install
before_script:
- yarn global add gulp
script:
- gulp test
notifications:
  slack:
    secure: sEPigkYODYIMz6vNGfvm6BhdCrLLEtcv9SNbsClxV0GaI5qvkEwdNR4qzaq0uJV0ofVyxts84vv1GVaDlT6xYnrZBi7Gu10IehXW08IaIGWTnfNzlbHEaHt5gOUUTG9B1MNtwWulSKA2Zuf52k2XikpI+LOvcy8qir7hemnR1pp/8aPvvllIz5qU41R10bbQJzl+fHmcrI5OD2jR9+0eZ8OPICfrf7u/rPb2zsfQmmYULkaCPF5W3MxgHVlyuyqRTULqMivmt5CgyVALkOEXnCo2mo02ID4Z38y1QBCKQzox0Lq2on66e89ZinIr+NkcI8Qs64EXW90xF5WD8ISndsPwKjk5RCaolaE2oAOOwnmWO7IbHKHFGkLNcoJ6RE9fK8kVjlvWqnzz0hkOQjnI3KeCiYQxjK9ldgHBGWXhCwMoNisTUdAp+vU/8W8nXKU5tZ+a3HsyCClLApZtrvoIK7R9z2Vvzca5RyqvLHxK8rDKI+5egKpaKFnubuVoNnsrS79yfRsCBvWYuott0DV8QArQ82ykqq20XJjZFstEzaY5il/hA5rxZtWqvK9ZO1X94kcGRT2nWdbeEniSIcrmu2hqluE10qPNJx8dTm0Rbo2NnESgcczJATZ/IE4aDJY1fFJFnzvywjMzjIZaCQdJDFMScaK9MU9X2auH3LxU7eQ=
deploy:
  skip_cleanup: true
  provider: npm
  email: ''
  api_key:
    secure: RV2YladFtLRayTeb0jiyfODEz+Ftv2kDGMNVUPhcoZtznwAAZooRGrUHZ3XvfJyWHaBQge87ZzvkOjAw8enUcYos0akyOVRGm33VJuB2hnLZerU+5sOLTQlTGkqLEd6rGvZCk2CAfAY7OronbGw1yMfWSp+sQiQRXH+FnfHDJ1H2L4nPiFcGK7mCMn6CgBkK+sy6EH8c3kjvVx5C5ofingBjPtumysPmZO1e+MvbtFKA0ntDb+DygWYBk71W1nrxQNbxEOViGX3N9Sk96Ftm1UmKYDvSzJv/7nIKFx3PC63k57ktLLDmksl7deXUcDFnK6MLZcKGKmkhu9ANBfGd3pCjDd2PiQBiFnc5PXcupqU/hitxCEUeIajMd1eK6aiMzt/Bc1A4eLZ4V6UZfUjS6fjBlwqXDku4oF3lFDwTCTj94TZbLmSIVAMJWAeYQqPw//sA03yfr+RBSAYOp6NCLYdfVC38d8Q5S21iNgQ0gwgIy+acquF6xDm/EA6NtxSxBFGWSTfPTr02MaCMUFrm1TZfiMjVij5yRxfWuHS9Olfdt9HUmiumzaYe96lS2xU+B5ItAOAtMjXhyutP/7tMX9WLCfIjf/UvtTj07xmU+JC6DSOThFQVVt2OtLUvUbSN96CCjsax7L9fpYw/JBFAR5SA+Nt+napHruUciVF/2ys=
  on:
    repo: goVerb/docker-deployer
