language: node_js
node_js:
- 8.9.0
branches:
  only:
  - master
install:
- yarn install
before_script:
- yarn global add gulp
script:
- gulp test
notifications:
  slack:
    secure: sEPigkYODYIMz6vNGfvm6BhdCrLLEtcv9SNbsClxV0GaI5qvkEwdNR4qzaq0uJV0ofVyxts84vv1GVaDlT6xYnrZBi7Gu10IehXW08IaIGWTnfNzlbHEaHt5gOUUTG9B1MNtwWulSKA2Zuf52k2XikpI+LOvcy8qir7hemnR1pp/8aPvvllIz5qU41R10bbQJzl+fHmcrI5OD2jR9+0eZ8OPICfrf7u/rPb2zsfQmmYULkaCPF5W3MxgHVlyuyqRTULqMivmt5CgyVALkOEXnCo2mo02ID4Z38y1QBCKQzox0Lq2on66e89ZinIr+NkcI8Qs64EXW90xF5WD8ISndsPwKjk5RCaolaE2oAOOwnmWO7IbHKHFGkLNcoJ6RE9fK8kVjlvWqnzz0hkOQjnI3KeCiYQxjK9ldgHBGWXhCwMoNisTUdAp+vU/8W8nXKU5tZ+a3HsyCClLApZtrvoIK7R9z2Vvzca5RyqvLHxK8rDKI+5egKpaKFnubuVoNnsrS79yfRsCBvWYuott0DV8QArQ82ykqq20XJjZFstEzaY5il/hA5rxZtWqvK9ZO1X94kcGRT2nWdbeEniSIcrmu2hqluE10qPNJx8dTm0Rbo2NnESgcczJATZ/IE4aDJY1fFJFnzvywjMzjIZaCQdJDFMScaK9MU9X2auH3LxU7eQ=
deploy:
  skip_cleanup: true
  provider: npm
  email: devadmin@goverb.com
  api_key:
    secure: BMzaggOTjhzfmJ4ETCPt0A9h82kDAVN1x/ShmmfFAVa/8A89x/yShtl4ARpu4ecr5GNgxCgBv2rRBxHNncCuwPRHBFsUJGJFFeG4tqtI3FkhFzhV4v1bqT75sluE4jCvbRMJOSzhd7sdFULly5STumrjiVgUaah0e8jdncH0tjGK1iaempHnGeq1IN73DlOmzhrmNNIOWRHfwlUzjTmKSN4awT0JWGFxs5CKfuxqgr38XIEADSe1RJYdURynIOtx6mHIfHxT51kLzWIG2/HGiIciNLf/jGS62dRCqeONLjbRokFmQSK9SqGMdG6pHkHRaoNM6nBw8/gVhhrch/yEEEJWFKf1MOP27XeZl1PoZpq1gdlxaF3yMtvyhfFSsbCEwYgt0mLMkBOGfqtmM/u6mdSuEKvdjSkfQC7IhjHNvE+iNVgXjpY1MLg/41LGVc4sFzAmOhPs++/bQc6jmyGJRIdMwFj3aYMwU9eARYC35VRA9slEVKcJqod91XHZYGC29sg6R6kJdZPp5dK1wItWHntmpj0RtANuXDPG5fz4PPct5zFFhNrmXXg5BZIvqw+3wQsIxoe/jMQmuZmZH87/SA2POKWzm2jxN3R9H5SqBRHy8oLraIIOy6/U3gfPa+YLDioNnG6Zk/ZPYkiZMh0ekHRBqlbYlwXjTIQv5eYiyxs=
  on:
    repo: goVerb/docker-deployer
