language: node_js
node_js:
- 6.9.1
branches:
  only:
  - master
install:
- npm install
before_script:
- npm install -g gulp
script:
- gulp test
- gulp npmrc
after_success:
- npm publish
env:
  global:
    secure: vy46KrQc1uAH//VY/nkhKSpdKFeQkw8pwLCGKOi+tXOxhvY92kbmbqU7Pr9rZIlhX8G4eHimct3BJHe+VrO1T9pTeZzKTqUAqOVzpE8NJ76iHCLja2xN2nf/zrJMe34nhz9O+yjD6w+K6f7M0kdi+pbXi5C0J4TOsFNpaQgIvt4vyqf8nH6eRe0b22NvM+XoFHgqlTXUMkGLw8bXX6bgzLs6/jpU8q8Nw3HxZnd6eAtfxWAzkzmDf2JPK4nJyUyneeUXE1SebRqHviqtNKStuO1fRtPLaX1bCFW/41HnRGexZdrb8lTiFZ3i9J2ylY5AYvbwU946M8d6zGc2cXtta6qMToKpPBKGKrE1ZWrJM5d8VxOZM64+g1I4P89syKhd+1Q+oyLDoxI1loX38h0E5eZWD9idiyjMPvDDO06AAhfpjXEUfaQpODi2PcRM3daO/wUOI0NPVBaJ29WuKyomdwk3mzE3FFrjvpdOGJ8EKoyNHvW/y3sDFBNKk39iL1UDJMrT5W84qpOerP5914lAbicWhVXVn2w+R9DX6ZWwzvvWvYhq3CaQO+nlolaT/ryJ+p4EAd1TvZZdx7dpEjzMI3Ivv5Nz0c/8MgKmR5gGKpjxhlNpgyaGwTyNS6qC9276PxJFbDTtngVQLGkpVgRwXAy0PKsoeWyZYUS6YZwk91c=
notifications:
  slack:
    secure: kiAOCGfmREq+HLlGoVESqOPpxBbGoI4WqZIeTazqclFF0jFqECZWpMuKY5PfUuwxmKDcEaWBNqRIJ01L94KGzu+IH60Capgcalhl1i2YvdnJMuEC4ukleyCjbsksSkWMjab4cK0EMdz/fhW21Uxfff372DtNia3AR4xLS0+JpKWFOzUcq3IZYeWN7VBIRZl/ShifC7/qV+xyILiwOdSoiSa24KREaChB4UNNh2mLblfQ8Nab1Wv2MtmuhoORLoSdG12OhBM50DC4xdlqRXaaNCg6O3AyAdzK6vW+ZFcSwVv6sbJSiFO+JUQIlqHxVqAJt1lBfGQgbImC/TSoaR2VrKIsr2uIX/1xaJogfJH36m65UhH1sHG8DgMc9H58LXgDDvPQy3Fa5qA2ukPwhZBsrw4+YvAz1pBBBYR/QxQgd6EHuHkVKhyTjLlDWCW7IOwZtVE8sUbkgmZl+Dqx0lsBk5dBbiqJD5j6EuY9TmZgpYA47EhiJGhPfaiFFxdqcfQwg2OmptrXPl27nHjVRgLp8kEbc62rQzVLVz4+3yhb8tkLuj+hvVygM6Fib6YJAVW1DNixbsV9BlZ+hjOcgGuhgG+X+kKSjAS7xNDaLhNAU+V/w2zMHpk12T/nvcCiDqPJawml/EHGYi25hzrrPyeioO1TrS+mbsWpOlqHDwI/1EM=
