language: node_js
node_js:
- 6.9.1
branches:
  only:
  - master
install:
- npm install
before_script:
- npm install -g gulp
script:
- gulp test
- gulp npmrc
after_success:
- npm publish
env:
  global:
    secure: d+knndvcBC2wJcqpHt5Nu+CVuPbxxH6oauibRYlizisebkp6mO3p3SQV21q9GjDVKuIuPbIGjEe/jd/J0fMXXJ3EWDcbKXsHu7QvRpB+9TOf5bZd8GeW3vICkhAhwVHRWRB+HG+e1eU0Kf8o96qP1SIVWj+f7iWODCVNqMeeP9HpXCC82xwWayRbF35MON3og3XrFBaCcYcti3oFcJ71DrhhWc4eF2sr6ndiF31pcJ2Ef3HnL+DA7ob7KqYl4lzVbCFVByvRom+TgYe1fEl3L67cmGL+RCjXNaUAJID4pyexl5KMOi9BZfxWpORHKp9CXlNAKNy0gf17FIHeL457m5ExvFD6tUiqxoLrv7kT51N5PpvIxRnuOA06sgRotzLR3z/icj9xXX33CpLDT5CGRazaFEIIAXwqgzlh3TWo2XK1PdxCrTmBVo0rE33/XQbTKT30mqcMAgql3ikNroFNgpyubOERV9w2/MtRyf9gJZ0Zw5CCdsWHkOLLVnlDDP20K4gASXw2O/gGe7wCoGGgFxgJyzyWLtzSkNUvZTZMQ6CtPuar8G2US8CDMDAQINUgOcc+2de+VLipUPpb3VIw9dnwkkCflq8r1OeK2zNionh7EsQEWIoFDxhS6YZakZ2J/xgao/xkjDH8HcHze9oFWCqgwg8GF1d6mZyoUG8pOhc=
notifications:
  slack:
    secure: kiAOCGfmREq+HLlGoVESqOPpxBbGoI4WqZIeTazqclFF0jFqECZWpMuKY5PfUuwxmKDcEaWBNqRIJ01L94KGzu+IH60Capgcalhl1i2YvdnJMuEC4ukleyCjbsksSkWMjab4cK0EMdz/fhW21Uxfff372DtNia3AR4xLS0+JpKWFOzUcq3IZYeWN7VBIRZl/ShifC7/qV+xyILiwOdSoiSa24KREaChB4UNNh2mLblfQ8Nab1Wv2MtmuhoORLoSdG12OhBM50DC4xdlqRXaaNCg6O3AyAdzK6vW+ZFcSwVv6sbJSiFO+JUQIlqHxVqAJt1lBfGQgbImC/TSoaR2VrKIsr2uIX/1xaJogfJH36m65UhH1sHG8DgMc9H58LXgDDvPQy3Fa5qA2ukPwhZBsrw4+YvAz1pBBBYR/QxQgd6EHuHkVKhyTjLlDWCW7IOwZtVE8sUbkgmZl+Dqx0lsBk5dBbiqJD5j6EuY9TmZgpYA47EhiJGhPfaiFFxdqcfQwg2OmptrXPl27nHjVRgLp8kEbc62rQzVLVz4+3yhb8tkLuj+hvVygM6Fib6YJAVW1DNixbsV9BlZ+hjOcgGuhgG+X+kKSjAS7xNDaLhNAU+V/w2zMHpk12T/nvcCiDqPJawml/EHGYi25hzrrPyeioO1TrS+mbsWpOlqHDwI/1EM=
