language: node_js
node_js:
- 8.9.0
branches:
  only:
  - master
install:
- yarn install
before_script:
- yarn global add gulp
script:
- gulp test
- gulp build
- gulp npmrc
- npm publish
notifications:
  slack:
    secure: sEPigkYODYIMz6vNGfvm6BhdCrLLEtcv9SNbsClxV0GaI5qvkEwdNR4qzaq0uJV0ofVyxts84vv1GVaDlT6xYnrZBi7Gu10IehXW08IaIGWTnfNzlbHEaHt5gOUUTG9B1MNtwWulSKA2Zuf52k2XikpI+LOvcy8qir7hemnR1pp/8aPvvllIz5qU41R10bbQJzl+fHmcrI5OD2jR9+0eZ8OPICfrf7u/rPb2zsfQmmYULkaCPF5W3MxgHVlyuyqRTULqMivmt5CgyVALkOEXnCo2mo02ID4Z38y1QBCKQzox0Lq2on66e89ZinIr+NkcI8Qs64EXW90xF5WD8ISndsPwKjk5RCaolaE2oAOOwnmWO7IbHKHFGkLNcoJ6RE9fK8kVjlvWqnzz0hkOQjnI3KeCiYQxjK9ldgHBGWXhCwMoNisTUdAp+vU/8W8nXKU5tZ+a3HsyCClLApZtrvoIK7R9z2Vvzca5RyqvLHxK8rDKI+5egKpaKFnubuVoNnsrS79yfRsCBvWYuott0DV8QArQ82ykqq20XJjZFstEzaY5il/hA5rxZtWqvK9ZO1X94kcGRT2nWdbeEniSIcrmu2hqluE10qPNJx8dTm0Rbo2NnESgcczJATZ/IE4aDJY1fFJFnzvywjMzjIZaCQdJDFMScaK9MU9X2auH3LxU7eQ=
env:
  global:
    secure: RgFNwrRQAC6KDCoKA/I55axfZ7IKJmq5ry1YbX7ViczFEUrWI6/8VVsfVSMc7xtVdpj/AuOAr5ue0ATI6xKQyuomN2eRrgwzuR9VDE1ConOAE7qj6tpP3DL7EVcRJ542kKBvKSY5ppi2tNbByEZOLh3qIkF0rrCG95DxannIuWxTDwUp6Sel+AUrhuWM4B6PLZh3Qi0bOOUzmTtZqEpTlV7vW5LDYcQKbubsvG+QNZJO2V4eN4Sf9k9wvR0kFSdMIpLBMxO5Rx1NYGB65Jpr1rySwtPX/mNlVy0eSodSVYtR7whHQJWk8cESfsJjrGaY960nHN3AGPp+s16LWauxlUgCbrRW1R15+x50aIhOuk3Ls4XJ6xq/qGnnXXVmu2LVW0YL2UjfuC3880rh4JrQcv6bJxJQFRwMKNOpf6s3IWUbGG4/ljQHgY7ODHjj/0pSf0Tb2DX+W+TjdaDpKgfSMsE5IOHTu2SjAcNOhhE6B/tA44Tm/YMdJZW2TrQ5VUun2FRiIuwiY0IRlgPd+gLdn7LLSLLbMTFHWZn4HpSLYvLj6ZyX9Z1dLLCj217ZuXUQI6yY1NsJ51EV6ecaTTS6CXs89TKwmf9r5zwBPgq5SPaLTA1W6pu3SD9c1uJJGyl5xkLvnte2hjIS+O2uSE7f3b1RS6sx4pPWRoBzF9TxB/I=
